apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment  # Set a name for the deployment
  labels:
    app: my-app
spec:
  replicas: 3  # Set the number of replicas for scaling
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: ghcr.io/my-org/my-repo:latest  # Replace with the actual image path
          imagePullPolicy: Always  # Image pull policy (Always, IfNotPresent, Never)
          ports:
            - containerPort: 80  # Replace with the port your app listens on
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: ENV_VAR_EXAMPLE  # Customize with your environment variables
              value: "example-value"
          volumeMounts:
            - name: my-volume
              mountPath: /mnt/data  # Customize mount path
      volumes:
        - name: my-volume
          emptyDir: {}  # Use emptyDir for ephemeral storage (customize as needed)

